### ISSUE TITLE
Epic: Load to Siv3D組み込み

### ISSUE THREAD

**Issue by falrnd** [falrnd/Sivngi#2]
https://github.com/Siv3D/OpenSiv3D/issues/485#issuecomment-1053340123
* [x] コンストラクタへの nodiscard は `SIV3D_NODISCARD_CXX20`
  * fixed: a898d3dcb134c62b907182154850016f41262314
* [x] #3
* [x] 層を動的に変えられるように
  * impl : 09a85a7aa17041bc6eb80c2a9e13779c7363db11
* [x] 消費しているメモリ量(概算)可視化
  * impl : 14b32f0bb03f8e3ecade1d5521176fc9de3f9f07
* [x] `using I16 = s3d::uint32;//s3d::uint16;` コンパクトなほうを選べばよい
  * fixed : ede6cf704c1c20f4fd8a1d2f6f3a71996bdff48f
